# Generated by Django 5.2.8 on 2025-11-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
